# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SharEats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SharEats
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Stripe'
  pod 'SideMenu'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.3'

  target 'SharEatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharEatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
